import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/Sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} h-screen `}>
        <div className="flex h-full border-r-green-500">
          <Sidebar />
          <div className="w-2 bg-green-500"></div>

          <div className="h-screen flex-1 bottom-0   ">{children}</div>
        </div>
      </body>
    </html>
  );
}
