import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/ThemeProvider";
import Sidebar from "@/components/Sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} h-screen `}>
        <ThemeProvider attribute="class" defaultTheme="system">
          <div className="flex h-full">
            <Sidebar />
            <div className="flex-1 p-4">{children}</div>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
